FROM owasp/zap2docker-stable

EXPOSE 8090

RUN run cat zap.sh

CMD [ \
  "zap-cli", \
  "quick-scan", \
  "--self-contained", \
  "--start-options", \
  "-config api.disablekey=true", \
  "http://webapp" && \
]
